### ISSUE TITLE
Improve infer function

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#105]
# Overview

See reference implementation - https://github.com/frictionlessdata/tableschema-js/pull/100. We have just to port it.

# Tasks
- [ ] make task list up-to-date
- [ ] pwalsh wrote:  I've noticed in OpenSpending over the last months how useful it would be to guessing full type + format,  and not just type, so this is good to capture in an issue (cc @akariv FYI)
- [ ] Input data should be checked to have corresponding to primary_key value column:
  def infer(headers, values, row_limit=None, explicit=False, primary_key=None):
- [x] it works slow because of using the whole type.test() method (I suppose with constraints checks etc) 
- [ ] it works slow because it does the full rows processing instead stopping when confident enough
- [ ] it could work slow because of `geojson` validation
- [ ] ensure empty cells not inferred to geojson https://github.com/frictionlessdata/tableschema-py/issues/117
 - [ ] if would be useful to guessing full type + format, and not just type- https://github.com/frictionlessdata/jsontableschema-py/issues/103
- [ ] other checks

---

@IsmiKin

I had been using Good Tables for a bit and now I was trying to start using this library also to infer the schemas.

For testing the example I found in the `goodtables-web` (I modified to don't be faulty)
```
Department,Entity,Date of Payment,Expense Type,Expense Area,Supplier,Transaction Number,Amount
Department of Data,Monitor,01-12-2015,Wrangling,Sector Development,Some Supplier 1,100,300
Department of Data,Monitor,01-11-2015,Visualization,Sector Development,Some Supplier 2,101,400
Department of Data,Monitor,03-10-2015,Cleaning,Sector Development,Some Supplier 3,102,400
```

I made a test to check if I get what I expect, and it sometimes and another not. It's because sometimes the infering guess the field `Amount` as `string` and another as `integer`. Also, another point it's that it can not guess that the field `Date of Payment` it's a date, it's always a `string`; I tried different date formats and all of them wasn't recognized.

Here it comes the code (extract from the CLI file):

```
def infer_schema(self, data, encoding='utf-8', row_limit=100):
        with io.open(data, mode='r+t', encoding=encoding) as stream:
            try:
                headers = stream.readline().rstrip('\n').split(',')
                values = tableschema.compat.csv_reader(stream)
            except UnicodeDecodeError:
                raise Exception("Could not decode the data file as {0}."
                                "Please specify an encoding to use with the "
                                "--encoding argument.".format(encoding))
            else:
                schema = tableschema.infer(
                    headers, values, row_limit=row_limit)

        return schema
```

And I get as response:
```
{
  "fields": [{
    "description": "",
    "format": "default",
    "type": "string",
    "name": "Department",
    "title": ""
  }, {
    "description": "",
    "format": "default",
    "type": "string",
    "name": "Entity",
    "title": ""
  }, {
    "description": "",
    "format": "default",
    "type": "string",
    "name": "Date of Payment",
    "title": ""
  }, {
    "description": "",
    "format": "default",
    "type": "string",
    "name": "Expense Type",
    "title": ""
  }, {
    "description": "",
    "format": "default",
    "type": "string",
    "name": "Expense Area",
    "title": ""
  }, {
    "description": "",
    "format": "default",
    "type": "string",
    "name": "Supplier",
    "title": ""
  }, {
    "description": "",
    "format": "default",
    "type": "integer",
    "name": "Transaction Number",
    "title": ""
  }, {
    "description": "",
    "format": "default",
    "type": "integer",
    "name": "Amount",
    "title": ""
  }]
}
```

Another observation, if a column it's not consistent (it means it has sometimes strings and another integer), the infering doesn't fail, it just choose one every time. Is it the expected behaviour? Shouldn't fail in that case? Would be good add a structural validation before do the infer schema?

**Comment by pwalsh** [comment]
@roll great thing to do, but not related to updating specs to v1. Please do not do until after updates related to specific v1 changes.

**Comment by roll** [comment]
MERGED
#80

**Comment by roll** [comment]
It's done in [Frictionless Framework](https://github.com/frictionlessdata/frictionless-p)
