### ISSUE TITLE
Introduce Schema.valid and Schema.errors

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#113]
# Overview

Ruby port use this approach to report a schema validation results. It could be useful for goodtables to have a chance to get this errors on table label. But it should be only as an option like this:

``` python
schema = Schema('descriptor.json', strict=False)
if not schema.valid:
    print(schema.errors)
```

Collecting errors instead of raising in the most cases is a bad idea (an user should do not forget to check it or could get into unpredictable state). But as an option it could be a nice interface.

``` python
schema = Schema('descriptor.json') # without flag raise first error
assert schema.valid == True # without flag always valid
```

# Tasks

- [ ] implement the plan above
- [ ] review/fix `validate` function 
  - [ ] it should suppose not retrieved descriptor (path/url)
  - [ ] pk/fk checks are in the incorrect place (it runs for all nested nodes)
- [ ] remove `fail_fast` from `validate`

**Comment by pwalsh** [comment]
@roll collecting errors makes sense in many cases. Similar libraries also collect errors, such as  [WT Forms](http://wtforms.readthedocs.io/en/latest/) and [JSON Schema](https://python-jsonschema.readthedocs.io/en/latest/validate/#jsonschema.IValidator.iter_errors).

I think here we are talking about errors in data, and not errors in code, and error collection is fine, and even much preferred to enable certain use cases (GoodTables is a good example of needing to collect errors).

**Comment by roll** [comment]
Even more precisely it's about schema validation error. And question mostly about what's API to have for it. For now of course it's possible too:

```python
try:
    validate(`descriptor.json`, no_fail_fast=True)
except MultipleInvalid as exception:
    print(exception.errors)
```

But goodtables uses as main unit `jsontableschema.Table` and for this class to instantiated with invalid schema is not possible for now.

**Comment by pwalsh** [comment]
so i'd say schema validation should always raise.


BTW why `no_fail_fast` instead of `fail_fast`. First is awkward.

**Comment by roll** [comment]
> so i'd say schema validation should always raise.
By default I agree. That's was my point.

About option naming yea I struggle a little bit with it. There is an intention to have flags false by default:
```
$ jsontableschema validate --no-fail-fast
```

**Comment by pwalsh** [comment]
@roll I dont want you to do this until after finishing the issues related to implementing spec changes.
