### ISSUE TITLE
Update Storage API based on SQL driver

### ISSUE THREAD

**Issue by akariv** [frictionlessdata/tableschema-py#136]
Right now the only way to update an existing dataset is to delete the table (or bucket) and recreate it with the new data.

This is problematic in many situations, especially when a single transaction is required to avoid any possibility of downtime.

---

# Tasks

- [ ] add `update_keys` argument to `Storage.write` method
- [ ] review Storage API for other needed additions (fix @abstractmethod missing?)
- [ ] reflect changes in documentation (as part of #80 documentation upgrage)
- [ ] mark Storage API as a provisional API

**Comment by pwalsh** [comment]
@akariv did you do any further work directly in openspending that is of relevance here?

**Comment by akariv** [comment]
Well, this was done in `jsontableschema-sql`  in these PRs:
frictionlessdata/jsontableschema-sql-py#53
frictionlessdata/jsontableschema-sql-py#55
frictionlessdata/jsontableschema-sql-py#57
frictionlessdata/jsontableschema-sql-py#60

However, we should still consider modifying the general storage API to add these concepts to other storage drivers as well (and not just the `sql` one).

**Comment by pwalsh** [comment]
@akariv great!

@roll it would be amazing to get this written up as a task for general driver refactoring.
