### ISSUE TITLE
Analyze spec-v1 and make corresponding updates

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#150]
# Overview

There is a many new stuff in http://specs.frictionlessdata.io/table-schema/ (v1) that should be analyzed and implemented (and not covered by existed issues):
- json pointers
- fmt -> {PATTERN}
- updated types
- new types
- etc

# Tasks

- [x] make analysis
- [x] split issue/implement if needed
- [x] upgrade to schemas from specs-v1
- [x] implement null/types/constraints behavior from specs-v1
- [x] ensure `topojson` type is supported (#65) (VALIDATION is backlogged - #158)
- [x] ensure `duration` type is supported (#38)
- [x] ~ensure correct work of degree/minute/second of geopoint (#66) (spec doesn't have it)~
- [x] add readme note about rebase to `specs-v1` + update docs (Field API)
- [x] provide feedback to specs
- [x] apply default to `Field`
- [x] `number` percentages should be divided by 100 
- [x] `number` default group should be null

**Comment by pwalsh** [comment]
We can skip topojson support. if we can't find an off-the-shelf JSON Schema to use to validate it (as we did for GEOJson), then we keep it on the backlog.

**Comment by pwalsh** [comment]
@roll note that JSON Pointer support is implemented in this lib https://github.com/stefankoegl/python-json-pointer
 We should be able to patch that to support JSON Pointers in the current descriptor only ("current descriptor" meaning the top-level descriptor of current context)
