### ISSUE TITLE
Replace `no_fail_fast` option, update exceptions

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-py#160]
We used to use `fail_fast` with a boolean value, to catch all errors, or return on first error. 

This keyword argument got changed to `no_fail_fast` which is difficult conceptually  - it feels like a double negative and make the user of the library think twice about the actual meaning.

I can't see any good reason for this change, and it only feels confusing. I suggest we change it back for the v1 release.

Any thoughts @amercader @akariv ?

---

# Tasks
- [ ] decide on fail fast
- [ ] CastRowError, CastValueError, ConstraintError(CastValueError) + deprecated InvalidCastError
- [ ] add fields to `CastValueError` `field_name/type/format/value`
- [ ] add fields to `ConstraintError` `field_name/constraint_type/constraint/value`
- [ ] remove not used exceptions

**Comment by roll** [comment]
@pwalsh 
I think we've already discussed it and agreed that `no_fail_fast` was a bad idea and should be changed. Me just `fail_fast` also is questionable because it a `flag that's true` be default. 

So use case for it like:
```
Field().cast_row(row, fail_fast=False)
```

I feel that more natural to have falsy by default flag like:
```
Field().cast_row(row, multiple_errors=True) -> raise MultipleInvalid
```

But just haven't good proposal for name. So have nothing against `fail_fast` is there is no better options.

**Comment by amercader** [comment]
`fail_fast` is not super intuitive either, what about `stop_on_error` ? I don't personally have much problem with default params being true, but if that's an issue you can use `continue_on_error` (or `stop_on_errors` / `continue_on_errors`, I don't know what makes more sense in this case)

**Comment by akariv** [comment]
How about `collect_all_errors`, false by default?

**Comment by roll** [comment]
I think even more important problem with this interface that this pramater (fail_fast) differ exception that should be expected (InvalidCastError to MultipleInvalid). So it could be confusing to user.

If we take a step back - why don't use interface just like this:
```python
try:
  field.cast_row(row)
except InvalidRowError as exception:
  for error in exception.errors:
    # every error is InvalidCastError
```
This function is not used in goodtables so performance-wise is ok.

And also it will be following `validate` API (raising an exception with a list of errors - which is WIP).

Ps. 
Sorry for formatting. From phone.
