### ISSUE TITLE
Update types blocked by specs

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#166]
# Overview

There is a few active issue in specs repository which could affect work with types. We have to wait those issues resolution (may be as specs-v1.1) and update the library accordingly. 

# Tasks

- [ ] follow decision on `year` type (https://github.com/frictionlessdata/specs/issues/401)
- [ ] follow decision on `number` type - https://github.com/frictionlessdata/specs/issues/393
- [ ] follow decision on `geopoint` type - https://github.com/frictionlessdata/specs/issues/400

**Comment by roll** [comment]
RESOLVED
