### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#80]
# Overview

Here is meta issue for tracking progress of jsontableschema `v1` release. Any thoughts, ideas and comments are welcome. See corresponding milestone for the list of included issues (just started to fill it).

# Tasks

- [x] backward-compatability check
- [x] review `jsontableschema-js` feedback to get related problems
- [x] review `duration` type external package usage (sync with `jsontableschema-js`)
- [x] ensure all deprecated code removed [-v1)
- [x] release ALPHA
---
- [x] reduce public API of `infer`for now (see JavaScript)
- [x] remove `alpha` from dependencies
- [x] rename `number` to `row_number` vars
- [x] mark `Storage` API as a provisional API
- [x] change `Schema.headers` to `Schema.field_names`
- [x] add `Table.headers` (as `schema.field_names`?)
- [x] `Table.__apply_processors` shouldn't change stream headers!
- [x] add `cast=True/False` flag to `Table.iter/read`
- [x] rename `specs` folder to `profiles` folder
- [x] sync `backend/storage=None, **options` naming to Stack Reference
- [x] create internal functions `retrieve_descriptor` and `expand_field/schema_descriptor`
- [x] remove `DEFAULT_DECIMAL/GROUP_CHAR` from internal `config`
- [x] remove `compat` (use `six`)
- [x] expose package version (init, CLI)
- [x] review readme
- [ ] release
