### ISSUE TITLE
Field/types integration with removing from public API

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#94]
# Overview

For now `Field` is just a thin wrapper over types. Also consider removing types/fields from public API.
# Tasks
- [x] ensure raising error on unsupported formar
- [x] ensure canonical native python cast value representation (value after cast always should have the same python type)
- [x] remove types.NullType
